name: celltraj3d_env
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.7
 - numpy
 - h5py
 - matplotlib
 - pyemma
 - sphinx_rtd_theme
 - Sphinx
 - pytest
 - scipy
 - pip
 - scikit-image
 - scipy
 - mahotas
 - umap-learn
 - pytorch
 - pandas
 - napari
 - scikit-learn
 - pygpcca

 - pip:
   - csaps
   - pystackreg
   - cellpose
   - btrack
   - adjustText
   - open3d==0.9.0
#   - napari-sam
