name: ilastik_env
channels:
  - ilastik-forge
  - conda-forge
  - defaults
dependencies:
 - pip
 - ilastik-forge::ilastik-core==1.4.1b22
# - numpy
# - h5py
# - matplotlib
# - scipy
# - scikit-image
# - scikit-learn
# - pandas
# - dask

# - pip:
#   - ray[default]
#   - celltraj
